version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: logs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logsdb
      MYSQL_USER: logsuser
      MYSQL_PASSWORD: logspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
